################################# Default configuration ###################
# provide your domain here
baseURL = "https://docs.mehrlms.ir/"
# theme
theme = "dot"
# site title
title = "سامانه آموزش مجازی مهر"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)

# unsafe html
[markup.goldmark.renderer]
unsafe= true

################################# navigation ################################
[[menu.main]]

#[[menu.main]]
#name = "سوالات متداول"
#url = "faq"
#weight = 1

[[menu.main]]
name = "ارتباط با ما"
url = "contact"
weight = 2

# Dropdown menu
[[menu.main]]
weight = 3
name = "مستندات"
hasChildren = true

  [[menu.main]]
  parent = "مستندات"
  name = "نصب سریع"
  url = "installation"
  weight = 1

  [[menu.main]]
  parent = "مستندات"
  name = "امکانات"
  url = "features"
  weight = 2

  [[menu.main]]
  parent = "مستندات"
  name = "قالب ها"
  url = "themes"
  weight = 3


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#02007e"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "Vazir"

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"
  
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "#"
  
[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "#"

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
home = "خانه"
copyright = "سامانه‌ی آموزش مجازی [مهر](https://mehrlms.ir)"

# banner
[Languages.en.params.banner]
title = "سامانه آموزش مجازی مهر"
subtitle = "آموزش جامع این سامانه را ملاحظه فرمایید و سوالات خود را با تیم ما در میان بگذارید"
bg_image = "images/banner.jpg"
placeholder = "سوالی دارید؟ "

# call to action
[Languages.en.params.cta]
enable = true
title = "جواب سوال خود را پیدا نکردید؟"
#content = "سوالات خود را با در میان بگذارید. همکاران ما در کوتاه ترین زمان ممکن پاسخ شما را خواهند داد."
# call to action button
[Languages.en.params.cta.button]
enable = true
label = "ارتباط با ما"
link = "contact"

languagedirection = "rtl"
